### ISSUE TITLE
Best practices TODO

### ISSUE THREAD

**Issue by anandbaburajan** [FOSS-Cell-GECPKD/image-stego#7]
### Code
* [x] Proper readable and maintable code with consistent spacing and indentation
* [x] Functions follow the "Do One Thing" rule (single-responsibility)
* [x] Followed DRY (Don’t Repeat Yourself)
* [x] Added comments wherever required
* [x] Proper naming conventions
* [x] Avoided deep nesting

### Readme
* [ ] Badges (similar to the Gitter badge. You can maybe use: https://shields.io/)
* [x] Description (why this project exists)
* [x] Features (working of the project)
* [ ] Setup (Quick start instructions with how to download and use your project)
* [x] Contributing (How can others contribute?)
* [ ] License ("This project is licensed under the <your license>")

### Tests and CI/CD
* [ ] Wrote tests
* [x] Deployed the project (if possible)
* [ ] Added CI/CD tools to your project (maybe CircleCI or TravisCI) (if possible)

**Comment by anandbaburajan** [comment]
@BreadGenie, @Ayshhh and @btkcodedev, great work and thanks for contributing! You're just left with a few items in your TODO! I also think the project's UI can be improved a bit more (is 'modern' the right word here?). Also, do you wish to rename your project and repo? For the Readme, I'd suggest to refer the readme [here](https://github.com/FOSS-Cell-GECPKD/Hide-it). Also, you can add a section in the readme for 'potential improvements'.
